server:
  port: 9000

spring:
  application:
    name: gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway
            client-secret: qEOHHvEeVgmnVOaBByJGFO5ZD4W5gcTn
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/myrealm
  cloud:
    gateway:
      routes:
        - id: hello-api
          uri: http://localhost:8081
          predicates:
            - Path=/hello
          filters:
            - TokenRelay